<<<<<<< HEAD
sudo: required
dist: trusty
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
language: node_js
node_js:
  - "4"
  - "5"
  - "6"
  - "node"
matrix:
  fast_finish: true
  allow_failures:
  - node_js: "4"
before_install:
  - npm i npm@^4 -g
install:
  - npm install
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3
script:
  - npm run ci:travis
cache:
  directories:
    - node_modules
=======
language: node_js
sudo: false
node_js:
  - "4.5.0"
  - "6.5.0"
env:
  - NODE_ENV=development
services:
  - mongodb

before_install:
  - npm i -g npm@'>=3.5.3'
  - npm -v
  - npm i -g bower
  - bower -v

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/08c84711c36e875930d0
      - https://hooks.slack.com/services/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
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: always     # default: false


>>>>>>> 321305737ef8cf17332a0e46a6cbe676dea203d4
